### ISSUE TITLE
การแตก task ต่าง ๆ ต้องใส่ใน project management tool ที่เลือกใน week ที่ 1

### ISSUE THREAD

**Issue by up1** [panupongth148/Project-SW-DEV-TOOLS-AND-ENV-Group4#6]
การแตก task ต่าง ๆ ต้องใส่ใน project management tool ที่เลือกใน week ที่ 1

**Comment by panupongth148** [comment]
https://trello.com/invite/b/MolSiWQj/bfb6f77bdb71bd97c59131e08340a069/task-board
